// Auto-generated by openapi-typescript. Run `bun run schema` to regenerate.
// cd apps/master && bun run schema

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export type components = Record<string, never>;
export type operations = Record<string, never>;
