// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Song from '../src/commands/song.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['song'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'song': Song
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'song': {
      name: 'song',
      description: 'Download song with audio and lyrics to public/songs',
      options: {
        'audioProvider': { type: 'z.enum.default', required: true, hasDefault: true, default: "ytdlp", description: 'Select audio provider', short: 'a', enumValues: ["ytdlp"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"ytdlp"}]}, validator: '(val) => true' },
        'lyricProvider': { type: 'z.enum.default', required: true, hasDefault: true, default: "lrclib", description: 'Select lyrics provider', short: 'l', enumValues: ["lrclib"], schema: {"type":"zod","method":"default","args":[{"type":"literal","value":"lrclib"}]}, validator: '(val) => true' },
        'url': { type: 'z.url', required: true, hasDefault: false, description: 'URL from provider', short: 'u', schema: {"type":"zod","method":"url","args":[]}, validator: '(val) => true' },
        'offset': { type: 'z.coerce.number.default', required: true, hasDefault: true, default: 0, description: 'Lyric offset in milliseconds (positive = delay lyrics)', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":906,"end":907,"loc":{"start":{"line":33,"column":43,"index":906},"end":{"line":33,"column":44,"index":907}},"extra":{"rawValue":0,"raw":"0"},"value":0}}]}, validator: '(val) => true' }
      },
      path: './src/commands/song'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
