/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check for ping services */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/song": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get audio from YouTube by id/url */
        get: operations["getSong"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description All scenes */
        get: operations["getScenes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signin/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sign in with GitHub
         * @description Redirects to GitHub OAuth consent screen. User will be prompted to authorize the application.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Where to redirect after successful login */
                    redirect_url?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to GitHub OAuth */
                302: {
                    headers: {
                        /** @description GitHub OAuth URL */
                        location?: unknown;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/callback/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub OAuth callback handler
         * @description GitHub redirects here after user authorization. Session is automatically created.
         */
        get: {
            parameters: {
                query: {
                    /** @description GitHub authorization code */
                    code: string;
                    /** @description State parameter for CSRF protection */
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to frontend with session established */
                302: {
                    headers: {
                        /** @description Session cookie */
                        "set-cookie"?: unknown;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid code or state */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current session
         * @description Returns the currently authenticated user and their session info.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user?: {
                                /** @example user_123 */
                                id?: string;
                                /** @example user@github.com */
                                email?: string;
                                /** @example Fox Developer */
                                name?: string;
                                /** @example https://avatars.githubusercontent.com/... */
                                image?: string;
                                /** Format: date-time */
                                createdAt?: string;
                            };
                            session?: {
                                token?: string;
                                /** Format: date-time */
                                expiresAt?: string;
                            };
                        };
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out
         * @description Invalidates the current user session.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully signed out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                        };
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @constant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": "OK";
                    "multipart/form-data": "OK";
                    "text/plain": "OK";
                };
            };
        };
    };
    getSong: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        videoId: string;
                        title?: string;
                        author?: string;
                        duration?: number;
                        audioUrl: string;
                        mimeType: string;
                        bitrate: number;
                    };
                    "multipart/form-data": {
                        videoId: string;
                        title?: string;
                        author?: string;
                        duration?: number;
                        audioUrl: string;
                        mimeType: string;
                        bitrate: number;
                    };
                    "text/plain": {
                        videoId: string;
                        title?: string;
                        author?: string;
                        duration?: number;
                        audioUrl: string;
                        mimeType: string;
                        bitrate: number;
                    };
                };
            };
        };
    };
    getScenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: number;
                        name: string;
                        bg: string;
                        message?: string;
                    }[];
                    "multipart/form-data": {
                        id: number;
                        name: string;
                        bg: string;
                        message?: string;
                    }[];
                    "text/plain": {
                        id: number;
                        name: string;
                        bg: string;
                        message?: string;
                    }[];
                };
            };
        };
    };
}
